blank_issues_enabled: true
contact_links:
  - name: Spørsmål om selve reiserådene
    url: https://www.regjeringen.no/no/tema/utenrikssaker/reiseinformasjon/velg-land/id2414273/
    about: Innholdet i reiserådene er UDs. Spørsmål om dem går til Utenriksdepartementet.
